spring:
  datasource:
    url: jdbc:h2:mem:vop_demo;MODE=LEGACY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

springdoc:
  api-docs.enabled: true
  swagger-ui.enabled: true

vop:
  security:
    # Allow API key only for local testing
    api-key:
      value: local-key
    web:
      permit-paths:
        - /public/**
        - /files/download/**

# H2 console (optional)
#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2
